server:
  port: 8001
  error:
    include-message: always
  servlet:
    context-path: /data-quality-dashboard

rserve:
  path:
  host: ${RservHost}
  port: ${RservPort}
  unix: true

files-manager:
  url: ${FilesManagerUrl}

dqd-database:
  dbms: ${SharedDbType}
  server: ${SharedDbHost}
  port: ${SharedDbPort}
  database: ${SharedDbName}
  schema: ${SharedDbDqdSchema}
  user: ${SharedDbDqdUser}
  password: ${SharedDbDqdPass}

spring:
  application:
    name: Data Quality Dashboard
  datasource:
    url: ${SharedDbUrl}
    username: ${SharedDbDqdUser}
    password: ${SharedDbDqdPass}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  cloud:
    azure:
      keyvault:
        secret:
          property-source-enabled: true
          property-sources:
            -
              credential:
                client-id: b54598c7-90a9-44b4-a67d-a8ee90a2b091
              endpoint: https://kv-perseus.vault.azure.net/
              profile:
                tenant-id: b376f6fd-26d6-4a47-8c9f-05e9bbff476c