server:
  port: 8001
  error:
    include-message: always
  servlet:
    context-path: /data-quality-dashboard

rserve:
  path:
  host: localhost
  port: 6311
  unix: true

files-manager:
  url: http://localhost:10500/files-manager

dqd-database:
  dbms: postgresql
  server: shareddb
  port: 5432
  database: shared
  schema: dqd
  user: dqd
  password: password

spring:
  application:
    name: Data Quality Dashboard
  datasource:
    url: jdbc:postgresql://localhost:5432/shared
    username: dqd
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: false
